apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-zqli
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-zqli
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-zqli
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-zqli
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-zqli
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-chqq-tenant/rhtap-demo-app/hacbs-test-project-zqli@sha256:2fe49fda3e82f2b1a3d4160a62ee59c69c99da10c81e5b0b791f01764a5824ed
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
