apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-zqli
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-chqq-tenant/rhtap-demo-app/hacbs-test-project-zqli@sha256:6c7379aca7be784a3841db14e07437395e81ae8bdb9bdda08e8f5847de7a8da5
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
